name: WhitelistRescue
version: ${project.version}
main: dev.josephzurowski.mcraft.whitelistrescue.Main
api-version: 1.13
authors: [Dunklheit]
description: For recovering a whitelist that is only contained in server memory
website: https://moonmoon.live

commands:
  recoverwl:
    usage: /recoverwl
    permission: whitelistrescue.recover
    description: Dumps the in-memory whitelist to a file

permissions:
  whitelistrescue.recover:
    description: Allows you to dump the in-memory whitelist to a file
    default: op
